name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 16
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Generate Bundle
        run: |
          npm i -g vite
          npm init vite@latest CodeEditor --template vanilla
      - name: Zip repo
        uses: vimtor/action-zip@v1
        with:
          files: /
          dest: CodeEditor.zip
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: CodeEditor.zip
          path: CodeEditor.zip
